version: "3.8"

services:
  # Next.js 애플리케이션
  nextjs:
    build: .
    container_name: phum-nextjs
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - .next:/app/.next
    networks:
      - app-network
    restart: unless-stopped

  # Nginx 리버스 프록시
  nginx:
    image: nginx:alpine
    container_name: phum-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - nextjs
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
